### ISSUE TITLE
Inconsistent exponent

### ISSUE THREAD

**Issue by ghost** [ppernot/ECDFT#1]
The code to generate the inversion probability data for table 3 appears to be erroneous.
According to Eq. (26) in the paper (P. Pernot, J. Chem. Phys. 148, 241707 (2018)), both variances (`UMUE`) should be squared. However, the R-code uses an exponent of one for the first variance in line 509:
`sd=sqrt(uMUE[meth1]^1+uMUE[meth2]^2)`
The results differ if an exponent of 2 is specified or if the corresponding inversion probability is bootstrap sampled.

**Comment by ppernot** [comment]
This is a bug indeed ! Thanks.
I am investigating the consequences on Table 3,
and will correct the code.

**Comment by ppernot** [comment]
Correction has been done in analysis.R and an Erratum has been sent to the editor.
The results in table III are significantly altered but sill lead to the same conclusion.

Thanks to the anonymous contributor ;-)
